services:
  mysql:
    image: mysql:latest
    container_name: timesheet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: timesheet
    ports:
      - "3306:3306"
    volumes:
      - timesheetvol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass123"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    image: timesheet-alamiwalyd-devops:latest
    container_name: timesheet-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/timesheet?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass123

volumes:
  timesheetvol:
